on:
  push:
    branches:
    - '!master'

name:  Pull Request build

jobs:

  build:
    name: Build
    container:
      image: maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build with Maven
        run: mvn package --file pom.xml
